export const PORTFOLIOS = 'PORTFOLIOS'
export const PORTFOLIOS_SUCCESS = 'PORTFOLIOS_SUCCESS'
export const PORTFOLIOS_FAILED = 'PORTFOLIOS_FAILED'

export const PORTFOLIO_DETAILS = 'PORTFOLIO_DETAILS'
export const PORTFOLIO_DETAILS_SUCCESS = 'PORTFOLIO_DETAILS_SUCCESS'
export const PORTFOLIO_DETAILS_FAILED = 'PORTFOLIO_DETAILS_FAILED'
