export const SCENARIOS = 'SCENARIOS'
export const SCENARIOS_SUCCESS = 'SCENARIOS_SUCCESS'
export const SCENARIOS_FAILED = 'SCENARIOS_FAILED'

export const SCENARIO_DETAILS = 'SCENARIO_DETAILS'
export const SCENARIO_DETAILS_SUCCESS = 'SCENARIO_DETAILS_SUCCESS'
export const SCENARIO_DETAILS_FAILED = 'SCENARIO_DETAILS_FAILED'

export const CHANGE_ACTIVE_SCENARIO = 'CHANGE_ACTIVE_SCENARIO'

export const CHANGE_SCENARIO_DETAILS = 'CHANGE_SCENARIO_DETAILS'

export const UPDATE_SCENARIO_DETAILS = 'UPDATE_SCENARIO_DETAILS'
export const UPDATE_SCENARIO_DETAILS_SUCCESS = 'UPDATE_SCENARIO_DETAILS_SUCCESS'
export const UPDATE_SCENARIO_DETAILS_FAILED = 'UPDATE_SCENARIO_DETAILS_FAILED'